#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.example.com
    depends_on:
      - couchdb
    networks:
      - basic

  couchdb:
    container_name: couchdb
    extends:
      file: base/docker-compose-base.yaml
      service: couchdb
    networks:
      - basic

  cli:
    container_name: cli
    extends:
      file: base/docker-compose-base.yaml
      service: vm2-cli
    volumes:
      - ../chaincode/:/opt/gopath/src/github.com/
    networks:
      - basic
    depends_on:
      - peer0.org1.example.com
      - couchdb
   
  cliDigiBank:
    container_name: cliDigiBank
    extends:
      file: base/docker-compose-base.yaml
      service: vm2-cli
    networks:
      - basic
    volumes:
      - ../digibank:/opt/gopath/src/github.com/
    depends_on:
      - peer0.org1.example.com
      - couchdb
      - cli
