#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
version: '2'

volumes:
  peer0.org1.example.com

networks:
  basic:

services:

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.org1.example.com
    depends_on:
      - couchdb
    networks:
      - basic

  couchdb:
    container_name: couchdb
    extends:
      file: base/docker-compose-base.yaml
      service: couchdb
    networks:
      - basic

  cli:
    container_name: cli
    extends:
      file: base/docker-compose-base.yaml
      service: vm2-cli
    volumes:
      - ../chaincode/:/opt/gopath/src/github.com/
      - /etc/hosts:/etc/hosts
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - basic
    depends_on:
      - peer0.org1.example.com
      - couchdb
   
  cliMagnetoCorp:
    container_name: cliMagnetoCorp
    extends:
      file: base/docker-compose-base.yaml
      service: vm2-cli
    networks:
      - basic
    volumes:
      - ../magnetocorp:/opt/gopath/src/github.com/
      - /etc/hosts:/etc/hosts
    depends_on:
      - peer0.org1.example.com
      - couchdb
      - cli
